applications:
  - name: app1
    repoURL: "https://github.com/jimoj/app1-test-helm"
    targetRevision: "main"
    path: "."
    destination:
      server: https://192.168.49.2:8443
      namespace: dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

 
