applications:
  - name: app1
    repoURL: "https://github.com/jimoj/app1-test-helm"
    targetRevision: "main"
    path: "."
    destination:
      server: kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

 
